skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
last_batch = "BakeGjtjwhpaZ8bwqDjGR4KeRZ2jBPLia4XJdbNaJsXP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
